// AUTOGENERATED by packages/release (bun run release:cli) — DO NOT EDIT BY HAND.
// COMMITTED on purpose (unlike the gitignored dist outputs): this pins the
// published CLI release that the cloud's /api/cli/binary route redirects to.
// Re-run the release pipeline, then commit this file.
//
// `tag: ""` means nothing is published yet — the route returns 503 until the
// first release run fills in the tag + checksums.

import type { TCliRelease } from "./release-types";

export const CLI_RELEASE: TCliRelease = {
  repo: "openllmsh/cli",
  tag: "v2.6.19",
  targets: [
    "darwin-arm64",
    "darwin-x64-baseline",
    "linux-x64-baseline",
    "linux-arm64",
  ],
  sha256: {
    "darwin-arm64":
      "3b79555988e7c974b6ec8ef868d6501b8d7205c49ee555f11b955474b2dd23d3",
    "darwin-x64-baseline":
      "dd69d44d9cc82daf166187120f9641394bfcbc07f1f46a7a08025839d00d5038",
    "linux-x64-baseline":
      "8ad5d23f6c26317b5cc62b6d9a5579244dd2a90aeaf1a36adedbfd8c149075da",
    "linux-arm64":
      "38143721d3f1d6e54215aa99153c0ca90062d22f7aaaabe8c1c9d81b45354e5f",
  },
};
