// AUTOGENERATED by packages/release (bun run release:cli) — DO NOT EDIT BY HAND.
// COMMITTED on purpose (unlike the gitignored dist outputs): this pins the
// published CLI release that the cloud's /api/cli/binary route redirects to.
// Re-run the release pipeline, then commit this file.
//
// `tag: ""` means nothing is published yet — the route returns 503 until the
// first release run fills in the tag + checksums.

import type { TCliRelease } from "./release-types";

export const CLI_RELEASE: TCliRelease = {
  repo: "openllmsh/cli",
  tag: "v2.6.20",
  targets: [
    "darwin-arm64",
    "darwin-x64-baseline",
    "linux-x64-baseline",
    "linux-arm64",
  ],
  sha256: {
    "darwin-arm64":
      "cb9abdf6444529f22dccb04f69be8d129bf92fa50fd85ba84f1999efd05e6886",
    "darwin-x64-baseline":
      "5718c95a3f4e208f55241a41d8bac5b43a20592a30f9cb6bb5a25201f19674de",
    "linux-x64-baseline":
      "58e60394571e884d67a4d5a9c946f339b36c6dc7a1d4318059584c65f4d85ba2",
    "linux-arm64":
      "7ce92a0cf0fc684ec1471f0d77ba863e340f7ca25c09f7399c2ba7552b3f8b3a",
  },
};
